// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/aud_audio_web_version_test.dart.
// coverage:ignore-file

/// The version of the `aud_audio_web` package.
const String audAudioWebVersion = '0.0.2';
